INSTRUCTIONS = '''
Your task is to answer questions from the course participants
based on the provided context.

Use the context to find relevant information and provide accurate
answers. If the answer is not found in the context,
respond with "I don't know."
'''

PROMPT_TEMPLATE = '''
QUESTION: {question}

CONTEXT:
{context}
'''.strip()

#For fucntion calling - LLM searches the DB
"""
search_tool = {
    "type": "function",
    "name": "search",
    "description": "Search the FAQ database for entries matching the given query.",
    "parameters": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": "Search query text to look up in the course FAQ."
            }
        },
        "required": ["query"],
        "additionalProperties": False
    }
}
"""
# The CORRECT structure:
search_tool = {
    "type": "function",  # <-- Don't forget this!
    "function": {        # <-- This wrapper is what the error is complaining about
        "name": "search",
        "description": "Search the FAQ database for entries matching the given query.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Search query text to look up in the course FAQ."
                }
            },
            "required": ["query"]
        }
    }
}


class RAGBase:

    def __init__(self, index, llm_client, model, instructions=INSTRUCTIONS, prompt_template=PROMPT_TEMPLATE, course='llm-zoomcamp'):
        self.index = index
        self.llm_client = llm_client
        self.instructions = instructions
        self.course = course
        self.prompt_template = prompt_template
        self.model = model

    def search(self, user_query, num_results=5):
        boost_dict = {'question': 3.0, 'section': 0.5}
        filter_dict = {'course': self.course}

        return self.index.search(user_query, num_results=num_results, boost_dict=boost_dict, filter_dict=filter_dict)

    def build_context(self, search_results):
        lines = []

        for doc in search_results:
            lines.append(doc['section'])
            lines.append('Q: ' + doc['question'])
            lines.append('A: ' + doc['answer'])
            lines.append('')

        return '\n'.join(lines).strip()

    def build_prompt(self, query, search_results):
        context = self.build_context(search_results)
        return self.prompt_template.format(question=query, context=context)

    def llm(self,prompt):
        message_history = [
        {'role': 'system', 'content': self.instructions},
        {'role': 'user', 'content': prompt}
        ]
        response = self.llm_client.chat.completions.create(model= self.model,messages= message_history, tools=[search_tool])
        # tool call
        call = response.choices[0].message

        return(call)

    def rag(self, user_query):
        
        message_object = self.llm(user_query)

        if message_object.tool_calls:
            print("Agent decided to execute tool call")
        
            for tool_call in message_object.tool_calls:
                if tool_call.function.name == "search":
                    import json
                    # Extract the query arguments generated by the model
                    function_args = json.loads(tool_call.function.arguments)
                    extracted_query = function_args.get("query")

                    print(f"📡 [Executing Tool] Searching index for: '{extracted_query}'")

                    #Execute SQLite search 
                    search_results = self.search(user_query)

                    prompt = self.build_prompt(user_query, search_results)

                    #call the client again to get the final answer using the context
                    final_response = self.llm_client.chat.completions.create(model = self.model, 
                                                                             messages = [{'role': 'system', 'content' : self.instructions},
                                                                                         {'role': 'user', 'content' : prompt}])


                    return final_response.choices[0].message.content
                
        return message_object.content
    
